CREATE TABLE `technical` (
  `uuid` int(11) NOT NULL AUTO_INCREMENT,
  `security_id` int(11) NOT NULL,
  `date` datetime NOT NULL,
  `sma` float NOT NULL,
  `ema` float NOT NULL,
  `macd` float NOT NULL,
  `macd_signal` float NOT NULL,
  `macd_hist` float NOT NULL,
  `stoch_slow_d` float NOT NULL,
  `stoch_slow_k` float NOT NULL,
  `rsi` float NOT NULL,
  `stochrsi_fast_k` float NOT NULL,
  `stochrsi_fast_d` float NOT NULL,
  `willr` float NOT NULL,
  `roc` float NOT NULL,
  `rocr` float NOT NULL,
  `bbands_lower` float NOT NULL,
  `bbands_upper` float NOT NULL,
  `bbands_middle` float NOT NULL,
  PRIMARY KEY (`uuid`),
  KEY `security_id` (`security_id`),
  CONSTRAINT `technical_ibfk_1` FOREIGN KEY (`security_id`) REFERENCES `security` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
